on: [push, pull_request]

jobs:
  lint:
    name: Package and release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@

      - name: Install Composer
        run: composer install
      
      - name: Lint
        run: |
          composer lint