on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "!v[0-9]+.[0-9]+.[0-9]+-"

jobs:
  build:
    name: Package and release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: shivammathur/setup-php@v2

    - name: Install Composer
      run: composer install

    - name: Install WP CLI dist archive
      run: composer global require wp-cli/dist-archive-command:2.0

    - name: Build release artifact
      run: |
        wp dist-archive ./ ./Refreshed_${{ github.ref_name }}.zip

    - name: Upload release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./Refreshed_${{ github.ref_name }}.zip
        asset_name: Refreshed_${{ github.ref_name }}.zip
        tag: ${{ github.ref_name }}
        release_name: Refreshed ${{ github.ref_name }}
        prerelease: false





    
      